name: Build
description: Build the project and analyze code quality with SonarQube
inputs:
  sonar-REDACTED:
    description: 'SonarQube REDACTED used to authenticate the analysis'
    required: true
  sonar-host-url:
    description: 'URL of the SonarQube server'
    required: true
  project-type:
    description: 'Type of project - python, javascript, or java'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Repository Name Variable
      shell: bash
      run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
    - name: Use Repository Name Variable
      shell: bash
      run: echo "Repository Name:${{ env.REPO_NAME }}"
    - name: Create SonarQube project
      shell: bash
      run: |
        curl --include --request POST -u ${{ inputs.sonar-REDACTED }}: '${{ inputs.sonar-host-url }}/api/projects/create?name=${{ env.REPO_NAME }}&project=${{ env.REPO_NAME }}'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create SonarQube properties file
      shell: bash
      run: |
        echo "sonar.projectKey=${{ env.REPO_NAME }}" > sonar-project.properties
        if [ "${{ inputs.project-type }}" = "python" ]; then
          echo "sonar.python.coverage.reportPaths=./coverage.xml" >> sonar-project.properties
        else
          echo "sonar.javascript.lcov.reportPaths=./coverage/lcov.info" >> sonar-project.properties
        fi
    - name: Generate code coverage report
      if: inputs.project-type == 'python'
      run: |
        echo "Generating code coverage report for Python project..."
        ls
        pip install pytest-cov coverage
        cat sonar-project.properties
        pytest --cov-report xml --cov=. **/**/*.py | true
        cat coverage.xml
      else if: inputs.project-type == 'javascript'
      run: |
        echo "Generating code coverage report for JavaScript project..."
        mkdir -p .nyc_output
        npm install -f
        npm install mocha -g
        ls
        npx nyc --reporter=lcov --exclude "node_modules/**" mocha *.js | true
        ls
        rm -rf node_modules
        cd coverage
        cat lcov.info
    - uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-REDACTED: ${{ inputs.sonar-REDACTED }}
        sonar-host-url: ${{ inputs.sonar-host-url }}
