name: Build
description: Build the project and analyze code quality with SonarQube
inputs:
  sonar-token:
    description: 'SonarQube token used to authenticate the analysis'
    required: true
  sonar-host-url:
    description: 'URL of the SonarQube server'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Repository Name Variable
      shell: bash
      run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
    - name: Use Repository Name Variable
      shell: bash
      run: echo "Repository Name:${{ env.REPO_NAME }}"
    - name: Create SonarQube project
      shell: bash
      run: |
        curl --include --request POST -u ${{ inputs.sonar-token }}: '${{ inputs.sonar-host-url }}/api/projects/create?name=${{ env.REPO_NAME }}&project=${{ env.REPO_NAME }}'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Create SonarQube properties file
      shell: bash
      run: echo "sonar.projectKey=${{ env.REPO_NAME }}" > sonar-project.properties
    - uses: sonarsource/sonarqube-scan-action@master
      with:
        sonar-token: ${{ inputs.sonar-token }}
        sonar-host-url: ${{ inputs.sonar-host-url }}
