name: build

on:
  push:
    branches:
      - master # or the name of your main branch
      
env:
  SONAR_TOKEN: squ_92ce500b4383353ef21219293c07ffff35128a09
  SONAR_HOST_URL: http://54.73.70.164:9000

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_repo_name.outputs.repo_name }}
    steps:
      - name: Get Repository Name
        id: get_repo_name
        run: echo "::set-output name=repo_name::$(basename ${{ github.repository }})"
      
      - name: Create SonarQube project
        id: create_sonar_project
        run: |
          curl --include --request POST -u ${{ env.SONAR_TOKEN }}: '${{ env.SONAR_HOST_URL }}/api/projects/create?name=${{ steps.get_repo_name.outputs.repo_name }}&project=${{ steps.get_repo_name.outputs.repo_name }}'
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create SonarQube properties file
        run: echo "sonar.projectKey=${{ steps.get_repo_name.outputs.repo_name }}" > sonar-project.properties

  sonarqube_scan:
    name: SonarQube Scan
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-token: ${{ env.SONAR_TOKEN }}
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          project-key: ${{ needs.build.outputs.repo_name }}
